import React, { useReducer } from 'react';
import { ProgressPageProps, Project } from '../../../interfaces/interface';
import Stack from '../../Stack/Stack';

import './ProgressPage.scss';

const projects: Project[] = [
    {
        name: 'Carcará',
        img: require('../../../imgs/projects/carcara.jpg'),
        stacks: ['Rust'],
        description: 'Carcará is a proof checker and elaborator for SMT proofs in the Alethe format.',
        url: 'https://github.com/ufmg-smite/carcara',
    },
    {
        name: 'CVC5',
        img: require('../../../imgs/projects/cvc5.png'),
        stacks: ['C++', 'Wasm'],
        description:
            'CVC5 is a tool for determining the satisfiability of a first order formula modulo a first order theory (or a combination of such theories).',
        url: 'https://github.com/cvc5/cvc5',
    },
    {
        name: 'Proof Visualizer',
        img: require('../../../imgs/projects/proof-visualizer.png'),
        stacks: ['C++', 'React', 'Type Script', 'Wasm'],
        description:
            'Web visualizer for proof certificates generated by CVC5, a SMT solver. This website provides customizable views through graphs and tables allowing better understanding of certificates and the operation of SMT solvers.',
        url: 'https://github.com/vinciusb/proof-visualizer',
    },
    {
        name: 'Classification using computational geometry',
        img: require('../../../imgs/projects/geometry.png'),
        stacks: ['Python'],
        description:
            'A study case of computational geometry where the classification problem is implemented in a different way.',
        url: 'https://github.com/vinciusb/TP1-A2',
    },
    {
        name: 'Weather App',
        img: require('../../../imgs/projects/weather.jpg'),
        stacks: ['React', 'Type Script'],
        description: 'A desktop and web weather app using an open weather API for custom climate info.',
        url: 'https://github.com/vinciusb/weather-app',
    },
];

const stacksInfos: { [s: string]: { img: string; level: number } } = {
    'C++': {
        img: require('../../../imgs/stacks/c++.png'),
        level: 3,
    },
    React: {
        img: require('../../../imgs/stacks/react.png'),
        level: 3,
    },
    Rust: {
        img: require('../../../imgs/stacks/rust.png'),
        level: 2,
    },
    'Type Script': {
        img: require('../../../imgs/stacks/typescript.png'),
        level: 3,
    },
    Wasm: {
        img: require('../../../imgs/stacks/wasm.png'),
        level: 1,
    },
    Python: {
        img: require('../../../imgs/stacks/python.png'),
        level: 2,
    },
};

const N_PROJECTS = projects.length;

const ProgressPage: React.FC<ProgressPageProps> = ({ className }: ProgressPageProps) => {
    const [count, setCount] = useReducer((state: number, mode: boolean): number => {
        if (mode) {
            return state === N_PROJECTS - 1 ? 0 : state + 1;
        }
        return state === 0 ? N_PROJECTS - 1 : state - 1;
    }, 0);

    const renderPoints = (): JSX.Element => {
        return (
            <div className="progress-points">
                {Array.from(Array(N_PROJECTS), (_, id) => (
                    <div key={id} className={'point ' + (id === count ? 'highlighted' : '')}></div>
                ))}
            </div>
        );
    };

    const renderProject = (i: number): JSX.Element => {
        const curProj = projects[i];
        return (
            <div className="main-frame">
                <img src={curProj.img} alt={curProj.name} />
                <div className="infos">
                    <div>
                        <h3>{curProj.name}</h3>
                        <p>{curProj.description}</p>
                    </div>
                    <a href={curProj.url} target="_blank" rel="noreferrer">
                        <div className="check-bt">
                            <span>Check</span>
                            <span>🡲</span>
                        </div>
                    </a>
                    <div className="stacks">
                        {curProj.stacks.map((s, id) => (
                            <Stack key={id} level={stacksInfos[s].level}>
                                <img src={stacksInfos[s].img} alt={s} />
                            </Stack>
                        ))}
                    </div>
                </div>
            </div>
        );
    };

    return (
        <div className={'progress-page ' + className}>
            <div className="portfolio secao">
                <h1>Most recent projects</h1>
                <div id="past" className="transition-button" onClick={() => setCount(false)}>
                    {'<'}
                </div>
                {renderProject(count)}
                <div id="next" className="transition-button" onClick={() => setCount(true)}>
                    {'>'}
                </div>
                {renderPoints()}
            </div>

            <div className="stacks secao"></div>
        </div>
    );
};

export default ProgressPage;
